name: Discord title configuration
description: Suggest changes to a title's appearance in Discord

# title: 
labels:
  - Discord title configuration
assignees:
  - samuelthomas2774

body:
  - type: input
    id: title-name
    attributes:
      label: Title name
      description: The full name of the title, exactly as it appears on a Nintendo Switch console or Nintendo eShop. If you are requesting a custom Discord application for this title, this will be used as it's name.
    validations:
      required: true

  - type: input
    id: publisher
    attributes:
      label: Publisher
      description: The name of the title's publisher. This isn't used in Discord activities or any other features; this is just used to categorise titles.
    validations:
      required: true

  - type: textarea
    id: title-ids
    attributes:
      label: Title IDs
      description: |
        Include all related title IDs and their names, for example any demos or other versions (such as regional variants and online/prerelease demos), from all Nintendo eShop regions, even if they are not available for download.

        If the title/s already has/have custom Discord configuration, you don't need to include all title IDs - just one to identify it. If the title hasn't been released yet and doesn't have a title ID, add a note in the other information section below, and the expected release date and links to Nintendo websites/Nintendo eShop NSUIDs.

        Application title IDs are 16 hexadecimal digits, and should start with `0100` and end with `0000`, `2000`, `4000`, `6000`, `8000`, `a000`, `c000` or `e000`.
      placeholder: |
        0100d2f00d5c0000 Nintendo Switch Sports
        01000ee017182000 Nintendo Switch Sports Online Play Test
        ...
    validations:
      required: true

  - type: textarea
    id: other-information
    attributes:
      label: Other information
      description: |
        Include any other relevant information, such as custom attributes that should be set for the title, or any changes that should be made to the existing configuration, or any other related titles that have/will be released.
    validations:
      required: true

  - type: checkboxes
    id: review-checklist
    attributes:
      label: Review checklist
      options:
        - label: No other open issues related to this title exist (if any issues do exist, add a comment/reaction to those instead of opening a new issue)
          required: true
        - label: I am requesting a custom Discord application for this title - this title is a very popular game and/or has high ratings, is currently available for purchase (or will be soon) in most Nintendo eShop regions, and it would be useful for a number of users to have it's own Discord application (I don't have any strict guidelines for which titles should have custom Discord applications - tick if you think the title should have it's own Discord application - I just want to keep the list short so I don't have to create 100s of Discord applications)
          required: false
